### ISSUE TITLE
Dedicated Exception for RateLimit reached and return of Retry-After value

### ISSUE THREAD

**Issue by holtkamp** [picqer/moneybird-php-client#101]
I know this is on the [ToDo-list](https://github.com/picqer/moneybird-php-client#todo), but having a dedicated issue makes it easier to reference from code 🤓 and might trigger someone to put effort in this / refer it from a Pull Request. Maybe I will have time to dive in to this after the summer.

**Comment by holtkamp** [comment]
It seems that in some cases, the TooManyRequestsException is not thrown properly. I "think" this is a problem at the MoneyBird API side, but wanted to report it here to be able to discuss it. The stack trace:

```
In Connection.php line 423:
                                                               
  [Picqer\Financials\Moneybird\Exceptions\ApiException (429)]  
  Error 429: <html>                                            
  <head><title>429 Too Many Requests</title></head>            
  <body bgcolor="white">                                       
  <center><h1>429 Too Many Requests</h1></center>              
  <hr><center>nginx</center>                                   
  </body>                                                      
  </html>                                                      
                                                               

Exception trace:
 Picqer\Financials\Moneybird\Connection->parseExceptionForErrorMessages() at /app/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Connection.php:229
 Picqer\Financials\Moneybird\Connection->patch() at /app/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Actions/Storable.php:38
 Picqer\Financials\Moneybird\Entities\Contact->update() at /app/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Actions/Storable.php:16
...
...
```

This https://github.com/picqer/moneybird-php-client/blob/3a5518699795fdc526e8a348fe4395196c9596ee/src/Picqer/Financials/Moneybird/Connection.php#L423 indicates that the error is not properly detected here: https://github.com/picqer/moneybird-php-client/blob/3a5518699795fdc526e8a348fe4395196c9596ee/src/Picqer/Financials/Moneybird/Connection.php#L434-L443

This happens "sometimes"... In other occasions / when running the same command a few minutes later, the error IS detected and a TooManyRequestsException is thrown:

```
 Error 429: Retry later : 
#0 /app/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Connection.php(421): Picqer\Financials\Moneybird\Connection->checkWhetherRateLimitHasBeenReached(Object(GuzzleHttp\Psr7\Response), 'Retry later\n') 
#1 /app/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Connection.php(193): Picqer\Financials\Moneybird\Connection->parseExceptionForErrorMessages(Object(GuzzleHttp\Exception\ClientException)) 
#2 /app/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Entities/Contact.php(83): Picqer\Financials\Moneybird\Connection->get('contacts/custom...')
```
I got the idea that "sometimes" the response does not contain the `Retry-After` header...

Will contact the MoneyBird team to discuss this.

**Comment by holtkamp** [comment]
Nevermind, it appeared that the ```TooManyRequestsException```was not processed properly in our userland code. 🤦‍♂️ 

Current approach seems to work nicely: 

```php
        /**
     * @see https://developer.moneybird.com/#responses
     * @see https://developer.moneybird.com/#throttling
     *
     * @param ApiException $apiException
     *
     * @throws ApiException
     */
    public function processApiException(ApiException $apiException): void
    {
        $this->logger->error($apiException->getMessage().': '.$apiException->getTraceAsString());

        if ($apiException instanceof TooManyRequestsException) {
            Assertion::integer($apiException->retryAfterNumberOfSeconds, 'unable to determine number of seconds to sleep');

            $this->logger->info('API request limit reached: sleep the indicated amount of {retryAfterNumberOfSeconds} seconds', array('retryAfterNumberOfSeconds' => $apiException->retryAfterNumberOfSeconds));

            \sleep($apiException->retryAfterNumberOfSeconds);

            $this->logger->info('done sleeping, the API should be available for requests again');

            return;
        }

        throw $apiException;
    }
```
