### ISSUE TITLE
Cant save contact (404 Not Found)

### ISSUE THREAD

**Issue by arkoe** [picqer/moneybird-php-client#68]
I get a 404 error while trying to save a contact. This is the code being used:

```
$connection = new \Picqer\Financials\Moneybird\Connection();
$connection->setRedirectUrl(site_url());
$connection->setClientId('clientid');
$connection->setClientSecret('secret');
// $connection->redirectForAuthorization();

$connection->setAuthorizationCode('authcode');
$connection->setAccessToken('accesstoken');

$connection->connect();

$moneybird = new \Picqer\Financials\Moneybird\Moneybird($connection);

// echo $connection->getAccessToken();

$contact = $moneybird->contact();

$contact->company_name = 'Picqer';
$contact->firstname = 'Stephan';
$contact->lastname = 'Groen';
$contact->save();
var_dump($contact);
```

Took the code from your .README file. Not sure where it is going wrong, this is the error message:

```

Fatal error: Uncaught exception 'Picqer\Financials\Moneybird\Exceptions\ApiException' with message 'Error 404: 404 Not Found' in /Applications/MAMP/htdocs/vlieglesdeal/wp-content/themes/vlieglesdeal/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Connection.php:387 Stack trace: #0 /Applications/MAMP/htdocs/vlieglesdeal/wp-content/themes/vlieglesdeal/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Connection.php(199): Picqer\Financials\Moneybird\Connection->parseExceptionForErrorMessages(Object(GuzzleHttp\Exception\ClientException)) #1 /Applications/MAMP/htdocs/vlieglesdeal/wp-content/themes/vlieglesdeal/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Actions/Storable.php(28): Picqer\Financials\Moneybird\Connection->post('contacts', '{"contact":{"co...') #2 /Applications/MAMP/htdocs/vlieglesdeal/wp-content/themes/vlieglesdeal/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Actions/Storable.php(19): Picqer\Financials\Moneybird\Entities\Contact->inse in /Applications/MAMP/htdocs/vlieglesdeal/wp-content/themes/vlieglesdeal/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Connection.php on line 387
```

This are my required dependencies in composer.json:

```
    "require": {
        "guzzlehttp/guzzle": "^6.2",
        "picqer/moneybird-php-client": "^0.7.2"
    },
```

**Comment by arkoe** [comment]
AdministrationId required...
